- name: Translate hieradata
  parse_tripleo_hiera:
    hieradata_file: '{{ hieradata_file }}'
    hieradata: '{{ hieradata }}'
    schema: '{{ schema }}'
  when:
    - hieradata or hieradata_file
    - schema
  register: result

- name: Set facts
  set_fact:
    '{{fact_variable}}': '{{result.conf_dict}}'
  when:
    - result.conf_dict is defined
    - fact_variable != ''
